use_frameworks!

target 'GCSwiftLabelView_Example' do
  pod 'GCSwiftLabelView', :path => '../'

  target 'GCSwiftLabelView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
